/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex('member').del()
  await knex('member').insert([
    { id: 1, first_name: 'Santa', last_name: 'Claus', email: "s.claus1@email.com", rank: "SPC1", username: "spc1forever", password_hash: "$2b$12$hig73jSR/ccryE0pNivX7.SqN4DeovW1jXK7Drnq9QxxIKQgiTnA6", organization_id: 1, admin: false, is_van_cert: true, is_sedan_cert: false, is_truck_cert: false, is_5_ton_cert: false, is_amrap_cert: false, is_hmmwv_cert: true, is_mobilizer_cert: false, is_patrol_cert: true, is_tank_cert: false, is_semitruck_cert: false, is_landrover_cert: false, is_forklift_cert: false },
    { id: 2, first_name: 'Jared', last_name: 'Zoeller', email: "jz@email.com", rank: "TSgt", username: "jzo", password_hash: "$2b$12$/PdDxfNcLeGf6Cgg09EkcOG2bfv3rhAGOjkfwSLyGvhN9eZGsRvOu", organization_id: 2, admin: true, is_van_cert: true, is_sedan_cert: false, is_truck_cert: false, is_5_ton_cert: false, is_amrap_cert: false, is_hmmwv_cert: false, is_mobilizer_cert: false, is_patrol_cert: false, is_tank_cert: false, is_semitruck_cert: false, is_landrover_cert: false, is_forklift_cert: false },
    { id: 3, first_name: 'Test', last_name: 'Testington', email: "t.testington1@email.com", rank: "SPC4", username: "test", password_hash: "$2b$12$YobH2WZ8idc6UdCtUHcJ3u70a9Dt.TS5edX/FVa.91hkyIIJ6IMVq", organization_id: 3, admin: true, is_van_cert: true, is_sedan_cert: false, is_truck_cert: false, is_5_ton_cert: false, is_amrap_cert: false, is_hmmwv_cert: false, is_mobilizer_cert: true, is_patrol_cert: false, is_tank_cert: false, is_semitruck_cert: true, is_landrover_cert: true, is_forklift_cert: false },
    { id: 4, first_name: 'Armand', last_name: 'Bringas', email: "armand.br@email.com", rank: "Sgt", username: "armabringas", password_hash: "$2b$12$YobH2WZ8idc6UdCtUHcJ3u70a9Dt.TS5edX/FVa.91hkyIIJ6IMVq", organization_id: 4, admin: true, is_van_cert: true, is_sedan_cert: false, is_truck_cert: true, is_5_ton_cert: false, is_amrap_cert: true, is_hmmwv_cert: false, is_mobilizer_cert: false, is_patrol_cert: true, is_tank_cert: false, is_semitruck_cert: false, is_landrover_cert: false, is_forklift_cert: false },
    { id: 5, first_name: 'Antonio', last_name: 'Ortega', email: "tony.ortega.59@email.com", rank: "SPC2", username: "tonyortega", password_hash: "$2b$12$YobH2WZ8idc6UdCtUHcJ3u70a9Dt.TS5edX/FVa.91hkyIIJ6IMVq", organization_id: 5, admin: false, is_van_cert: true, is_sedan_cert: false, is_truck_cert: true, is_5_ton_cert: false, is_amrap_cert: true, is_hmmwv_cert: false, is_mobilizer_cert: false, is_patrol_cert: false, is_tank_cert: false, is_semitruck_cert: false, is_landrover_cert: false, is_forklift_cert: false },
    { id: 6, first_name: 'Christopher', last_name: 'Silverton', email: "silverton.chris.12@email.com", rank: "Col", username: "slicksilver", password_hash: "$2b$12$YobH2WZ8idc6UdCtUHcJ3u70a9Dt.TS5edX/FVa.91hkyIIJ6IMVq", organization_id: 6, admin: false, is_van_cert: true, is_sedan_cert: false, is_truck_cert: true, is_5_ton_cert: false, is_amrap_cert: true, is_hmmwv_cert: false, is_mobilizer_cert: false, is_patrol_cert: false, is_tank_cert: false, is_semitruck_cert: false, is_landrover_cert: false, is_forklift_cert: true },
    { id: 7, first_name: 'Matthew', last_name: 'Wegenke', email: "mattew.wegenke.galvanize@email.com", rank: "Maj", username: "mattewtheinstructor", password_hash: "$2b$12$YobH2WZ8idc6UdCtUHcJ3u70a9Dt.TS5edX/FVa.91hkyIIJ6IMVq", organization_id: 7, admin: false, is_van_cert: true, is_sedan_cert: false, is_truck_cert: true, is_5_ton_cert: true, is_amrap_cert: true, is_hmmwv_cert: true, is_mobilizer_cert: true, is_patrol_cert: false, is_tank_cert: false, is_semitruck_cert: false, is_landrover_cert: true, is_forklift_cert: false },
    { id: 8, first_name: 'George', last_name: 'Mihov', email: "george.mihov@email.com", rank: "TSgt", username: "georgemihovtheinstrutor", password_hash: "$2b$12$YobH2WZ8idc6UdCtUHcJ3u70a9Dt.TS5edX/FVa.91hkyIIJ6IMVq", organization_id: 8, admin: false, is_van_cert: true, is_sedan_cert: false, is_truck_cert: true, is_5_ton_cert: false, is_amrap_cert: true, is_hmmwv_cert: false, is_mobilizer_cert: false, is_patrol_cert: false, is_tank_cert: false, is_semitruck_cert: false, is_landrover_cert: false, is_forklift_cert: false },
    { id: 9, first_name: 'Lorenzo', last_name: 'Ross', email: "lorenzor@email.com", rank: "MSgt", username: "lrzzoross", password_hash: "$2b$12$YobH2WZ8idc6UdCtUHcJ3u70a9Dt.TS5edX/FVa.91hkyIIJ6IMVq", organization_id: 9, admin: false, is_van_cert: true, is_sedan_cert: false, is_truck_cert: false, is_5_ton_cert: false, is_amrap_cert: true, is_hmmwv_cert: false, is_mobilizer_cert: false, is_patrol_cert: false, is_tank_cert: false, is_semitruck_cert: false, is_landrover_cert: false, is_forklift_cert: true },
    { id: 10, first_name: 'Adam', last_name: 'Clay', email: "adam.clay.coder@email.com", rank: "MSgt", username: "claydough", password_hash: "$2b$12$YobH2WZ8idc6UdCtUHcJ3u70a9Dt.TS5edX/FVa.91hkyIIJ6IMVq", organization_id: 1, admin: false, is_van_cert: true, is_sedan_cert: false, is_truck_cert: true, is_5_ton_cert: false, is_amrap_cert: true, is_hmmwv_cert: true, is_mobilizer_cert: false, is_patrol_cert: true, is_tank_cert: false, is_semitruck_cert: false, is_landrover_cert: false, is_forklift_cert: false },
    { id: 11, first_name: 'Caroline', last_name: 'Clark', email: "caroline.cc@email.com", rank: "Sgt", username: "caroline", password_hash: "$2b$12$YobH2WZ8idc6UdCtUHcJ3u70a9Dt.TS5edX/FVa.91hkyIIJ6IMVq", organization_id: 2, admin: false, is_van_cert: true, is_sedan_cert: false, is_truck_cert: true, is_5_ton_cert: false, is_amrap_cert: true, is_hmmwv_cert: true, is_mobilizer_cert: false, is_patrol_cert: true, is_tank_cert: false, is_semitruck_cert: false, is_landrover_cert: true, is_forklift_cert: false },
    { id: 12, first_name: 'Charlie', last_name: 'Pearson', email: "charlie.pearson.60@email.com", rank: "1LT", username: "lanteen", password_hash: "$2b$12$YobH2WZ8idc6UdCtUHcJ3u70a9Dt.TS5edX/FVa.91hkyIIJ6IMVq", organization_id: 3, admin: true, is_van_cert: true, is_sedan_cert: false, is_truck_cert: true, is_5_ton_cert: true, is_amrap_cert: true, is_hmmwv_cert: true, is_mobilizer_cert: true, is_patrol_cert: false, is_tank_cert: false, is_semitruck_cert: true, is_landrover_cert: false, is_forklift_cert: false }
  ]);
};